import {
  DeliveryPackage,
  DriverProfile,
  FreightDemand,
  CompanyProfile,
  Review,
  AppNotification,
  NotificationPreferences,
} from '../types';

export const INITIAL_DRIVER: DriverProfile = {
  id: 'drv-01',
  name: 'Carlos Eduardo Silva',
  phone: '(11) 98765-4321',
  email: 'carlos.entregador@rotaexpress.com.br',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  rating: 4.95,
  totalDeliveries: 1420,
  cnhStatus: 'verified',
  crlvStatus: 'verified',
  efficiencyTier: 'Diamante',
  efficiencyScore: 98,
  fuelSavedLiters: 146.5,
  isOnline: true,
  currentLat: -23.55052,
  currentLng: -46.633308,
  vehicle: {
    type: 'moto',
    label: 'Honda CG 160 Cargo',
    model: 'Honda CG 160 (2024)',
    plate: 'BRA-2E19',
    avgConsumptionKmPerL: 38,
    fuelType: 'gasolina',
    fuelPricePerL: 5.89,
  },
};

export const DEFAULT_DRIVER = INITIAL_DRIVER;

export const DEPOT_ORIGIN = {
  name: 'Hub Central Logístico SP (Lapa)',
  address: 'Av. Ermano Marchetti, 1000 - Água Branca, São Paulo - SP',
  coordinates: {
    lat: -23.51864,
    lng: -46.69082,
  },
};

// 20 Sample packages spread realistically across São Paulo
export const SAMPLE_PACKAGES_SP: DeliveryPackage[] = [
  {
    id: 'pkg-01',
    trackingCode: 'ROTA-BR83921-SP',
    recipientName: 'Mariana Duarte Souza',
    recipientPhone: '(11) 99123-4567',
    address: 'Rua Augusta, 1492, Apto 42',
    neighborhood: 'Consolação',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01304-001',
    coordinates: { lat: -23.55678, lng: -46.66012 },
    weightKg: 1.2,
    volumeCategory: 'Pequeno',
    freightFee: 16.5,
    companyName: 'E-commerce Moda Bella',
    deliveryStatus: 'pending',
    specialInstructions: 'Deixar na portaria com Seu Antônio.',
  },
  {
    id: 'pkg-02',
    trackingCode: 'ROTA-BR99412-SP',
    recipientName: 'Felipe Albuquerque Ribeiro',
    recipientPhone: '(11) 98456-1122',
    address: 'Av. Brigadeiro Faria Lima, 2232',
    neighborhood: 'Jardim Paulistano',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01451-000',
    coordinates: { lat: -23.57891, lng: -46.69123 },
    weightKg: 3.5,
    volumeCategory: 'Médio',
    freightFee: 22.0,
    companyName: 'TechStore Brasil',
    deliveryStatus: 'pending',
    specialInstructions: 'Prédio comercial, recepção 3º andar.',
  },
  {
    id: 'pkg-03',
    trackingCode: 'ROTA-BR10482-SP',
    recipientName: 'Juliana Castro Pinto',
    recipientPhone: '(11) 97321-9988',
    address: 'Alameda Santos, 800',
    neighborhood: 'Cerqueira César',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01418-100',
    coordinates: { lat: -23.56812, lng: -46.65478 },
    weightKg: 0.8,
    volumeCategory: 'Pequeno',
    freightFee: 15.0,
    companyName: 'Farmácia Vida & Saúde',
    deliveryStatus: 'pending',
    specialInstructions: 'Medicamentos frágeis. Não inclinar.',
  },
  {
    id: 'pkg-04',
    trackingCode: 'ROTA-BR55231-SP',
    recipientName: 'Roberto Mendes de Oliveira',
    recipientPhone: '(11) 98111-7744',
    address: 'Rua Fradique Coutinho, 550',
    neighborhood: 'Pinheiros',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '05416-000',
    coordinates: { lat: -23.56145, lng: -46.68532 },
    weightKg: 2.1,
    volumeCategory: 'Médio',
    freightFee: 18.0,
    companyName: 'Livraria Dom Quixote',
    deliveryStatus: 'pending',
    specialInstructions: 'Campainha da casa 2.',
  },
  {
    id: 'pkg-05',
    trackingCode: 'ROTA-BR33819-SP',
    recipientName: 'Beatriz Vasconcelos',
    recipientPhone: '(11) 99455-8833',
    address: 'Av. Paulista, 1578',
    neighborhood: 'Bela Vista',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01310-200',
    coordinates: { lat: -23.56149, lng: -46.65588 },
    weightKg: 1.5,
    volumeCategory: 'Pequeno',
    freightFee: 17.5,
    companyName: 'E-commerce Moda Bella',
    deliveryStatus: 'pending',
    specialInstructions: 'Horário comercial até 18h.',
  },
  {
    id: 'pkg-06',
    trackingCode: 'ROTA-BR77412-SP',
    recipientName: 'Lucas Ferreira Guimarães',
    recipientPhone: '(11) 98234-9911',
    address: 'Rua Harmonia, 310',
    neighborhood: 'Vila Madalena',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '05435-000',
    coordinates: { lat: -23.55321, lng: -46.69245 },
    weightKg: 4.8,
    volumeCategory: 'Médio',
    freightFee: 24.0,
    companyName: 'Mundo Fitness Suplementos',
    deliveryStatus: 'pending',
  },
  {
    id: 'pkg-07',
    trackingCode: 'ROTA-BR88201-SP',
    recipientName: 'Camila Pires da Rocha',
    recipientPhone: '(11) 97120-4499',
    address: 'Rua Domingos de Morais, 1850',
    neighborhood: 'Vila Mariana',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '04036-000',
    coordinates: { lat: -23.59123, lng: -46.63845 },
    weightKg: 2.0,
    volumeCategory: 'Médio',
    freightFee: 19.0,
    companyName: 'Cosméticos Glow',
    deliveryStatus: 'pending',
  },
  {
    id: 'pkg-08',
    trackingCode: 'ROTA-BR44192-SP',
    recipientName: 'Thiago Nogueira Gomes',
    recipientPhone: '(11) 98662-3300',
    address: 'Rua Vergueiro, 3185',
    neighborhood: 'Chácara Klabin',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '04101-300',
    coordinates: { lat: -23.58512, lng: -46.63211 },
    weightKg: 1.1,
    volumeCategory: 'Pequeno',
    freightFee: 16.0,
    companyName: 'TechStore Brasil',
    deliveryStatus: 'pending',
  },
  {
    id: 'pkg-09',
    trackingCode: 'ROTA-BR99318-SP',
    recipientName: 'Aline Barbosa Lima',
    recipientPhone: '(11) 99512-8877',
    address: 'Av. Dr. Arnaldo, 1200',
    neighborhood: 'Sumaré',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01255-000',
    coordinates: { lat: -23.54891, lng: -46.67891 },
    weightKg: 0.5,
    volumeCategory: 'Pequeno',
    freightFee: 14.5,
    companyName: 'Documentos Express',
    deliveryStatus: 'pending',
  },
  {
    id: 'pkg-10',
    trackingCode: 'ROTA-BR66219-SP',
    recipientName: 'Gustavo Henrique Santos',
    recipientPhone: '(11) 98319-7722',
    address: 'Rua Heitor Penteado, 1020',
    neighborhood: 'Perdizes',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '05437-000',
    coordinates: { lat: -23.54231, lng: -46.68912 },
    weightKg: 6.2,
    volumeCategory: 'Grande',
    freightFee: 28.0,
    companyName: 'Auto Peças Express',
    deliveryStatus: 'pending',
  },
  {
    id: 'pkg-11',
    trackingCode: 'ROTA-BR11928-SP',
    recipientName: 'Patrícia de Oliveira',
    recipientPhone: '(11) 99881-2233',
    address: 'Rua da Consolação, 2400',
    neighborhood: 'Cerqueira César',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01301-100',
    coordinates: { lat: -23.55891, lng: -46.66211 },
    weightKg: 1.8,
    volumeCategory: 'Médio',
    freightFee: 17.0,
    companyName: 'E-commerce Moda Bella',
    deliveryStatus: 'pending',
  },
  {
    id: 'pkg-12',
    trackingCode: 'ROTA-BR33918-SP',
    recipientName: 'Marcelo Siqueira Prado',
    recipientPhone: '(11) 97721-6644',
    address: 'Rua Oscar Freire, 1100',
    neighborhood: 'Jardins',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01426-001',
    coordinates: { lat: -23.56381, lng: -46.66989 },
    weightKg: 0.9,
    volumeCategory: 'Pequeno',
    freightFee: 16.0,
    companyName: 'Joalheria Aurora',
    deliveryStatus: 'pending',
  },
  {
    id: 'pkg-13',
    trackingCode: 'ROTA-BR55829-SP',
    recipientName: 'Fernanda Martins Costa',
    recipientPhone: '(11) 98112-9900',
    address: 'Rua Teodoro Sampaio, 1800',
    neighborhood: 'Pinheiros',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '05406-150',
    coordinates: { lat: -23.56012, lng: -46.68219 },
    weightKg: 3.1,
    volumeCategory: 'Médio',
    freightFee: 20.0,
    companyName: 'Livraria Dom Quixote',
    deliveryStatus: 'pending',
  },
  {
    id: 'pkg-14',
    trackingCode: 'ROTA-BR44821-SP',
    recipientName: 'Rodrigo Brandão Silva',
    recipientPhone: '(11) 99332-1188',
    address: 'Rua Clélia, 1500',
    neighborhood: 'Lapa',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '05042-000',
    coordinates: { lat: -23.52678, lng: -46.69123 },
    weightKg: 5.0,
    volumeCategory: 'Médio',
    freightFee: 21.0,
    companyName: 'Auto Peças Express',
    deliveryStatus: 'pending',
  },
  {
    id: 'pkg-15',
    trackingCode: 'ROTA-BR99182-SP',
    recipientName: 'Renata Albuquerque Lima',
    recipientPhone: '(11) 98443-7766',
    address: 'Rua Cerro Corá, 890',
    neighborhood: 'Alto de Pinheiros',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '05061-150',
    coordinates: { lat: -23.54129, lng: -46.70891 },
    weightKg: 2.4,
    volumeCategory: 'Médio',
    freightFee: 19.5,
    companyName: 'Cosméticos Glow',
    deliveryStatus: 'pending',
  },
  {
    id: 'pkg-16',
    trackingCode: 'ROTA-BR77391-SP',
    recipientName: 'Bruno Alcantara Dias',
    recipientPhone: '(11) 97665-4422',
    address: 'Rua Turiassu, 650',
    neighborhood: 'Perdizes',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '05005-000',
    coordinates: { lat: -23.53123, lng: -46.67456 },
    weightKg: 1.6,
    volumeCategory: 'Pequeno',
    freightFee: 16.5,
    companyName: 'TechStore Brasil',
    deliveryStatus: 'pending',
  },
  {
    id: 'pkg-17',
    trackingCode: 'ROTA-BR66491-SP',
    recipientName: 'Larissa Fontes Xavier',
    recipientPhone: '(11) 99221-5588',
    address: 'Rua Bela Cintra, 1900',
    neighborhood: 'Consolação',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01415-002',
    coordinates: { lat: -23.55981, lng: -46.66312 },
    weightKg: 1.3,
    volumeCategory: 'Pequeno',
    freightFee: 16.0,
    companyName: 'E-commerce Moda Bella',
    deliveryStatus: 'pending',
  },
  {
    id: 'pkg-18',
    trackingCode: 'ROTA-BR22819-SP',
    recipientName: 'Vanessa Prado Medeiros',
    recipientPhone: '(11) 98771-3344',
    address: 'Av. Rebouças, 1400',
    neighborhood: 'Pinheiros',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '05402-100',
    coordinates: { lat: -23.56712, lng: -46.67912 },
    weightKg: 2.8,
    volumeCategory: 'Médio',
    freightFee: 18.5,
    companyName: 'Farmácia Vida & Saúde',
    deliveryStatus: 'pending',
  },
  {
    id: 'pkg-19',
    trackingCode: 'ROTA-BR11492-SP',
    recipientName: 'Diego Cavalcante Ramos',
    recipientPhone: '(11) 99119-8800',
    address: 'Rua Pamplona, 1050',
    neighborhood: 'Jardim Paulista',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01405-001',
    coordinates: { lat: -23.56612, lng: -46.65789 },
    weightKg: 4.0,
    volumeCategory: 'Médio',
    freightFee: 21.0,
    companyName: 'Mundo Fitness Suplementos',
    deliveryStatus: 'pending',
  },
  {
    id: 'pkg-20',
    trackingCode: 'ROTA-BR88319-SP',
    recipientName: 'Sabrina Toledo Viana',
    recipientPhone: '(11) 98334-1199',
    address: 'Rua Cardeal Arcoverde, 1200',
    neighborhood: 'Pinheiros',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '05408-001',
    coordinates: { lat: -23.55812, lng: -46.68723 },
    weightKg: 1.4,
    volumeCategory: 'Pequeno',
    freightFee: 16.5,
    companyName: 'Cosméticos Glow',
    deliveryStatus: 'pending',
  },
];

export const SAMPLE_FREIGHT_DEMANDS: FreightDemand[] = [
  {
    id: 'frt-101',
    companyName: 'Centro de Distribuição Mercado Express SP',
    title: 'Lote de Entregas E-commerce - Zona Oeste / Centro SP',
    originAddress: 'Av. Ermano Marchetti, 1000 - Lapa, São Paulo - SP',
    originCoordinates: { lat: -23.51864, lng: -46.69082 },
    totalPackages: 20,
    totalWeightKg: 46.5,
    totalDistanceEstKm: 34.8,
    totalPayout: 368.0,
    suggestedVehicle: 'moto',
    status: 'available',
    createdAt: '2026-08-30T10:15:00Z',
    packages: SAMPLE_PACKAGES_SP,
  },
  {
    id: 'frt-102',
    companyName: 'Farmácias DrogaExpress 24h',
    title: 'Entregas Urgentes de Medicamentos - Paulista & Jardins',
    originAddress: 'Rua Pamplona, 500 - Jardim Paulista, São Paulo - SP',
    originCoordinates: { lat: -23.56412, lng: -46.65489 },
    totalPackages: 8,
    totalWeightKg: 11.2,
    totalDistanceEstKm: 16.5,
    totalPayout: 145.0,
    suggestedVehicle: 'moto',
    status: 'available',
    createdAt: '2026-08-30T11:45:00Z',
    packages: SAMPLE_PACKAGES_SP.slice(0, 8),
  },
  {
    id: 'frt-103',
    companyName: 'Mega Peças Automotivas VUC',
    title: 'Distribuição B2B de Autopeças - Lote Pesado',
    originAddress: 'Rua Guaicurus, 120 - Água Branca, São Paulo - SP',
    originCoordinates: { lat: -23.5221, lng: -46.689 },
    totalPackages: 12,
    totalWeightKg: 280.0,
    totalDistanceEstKm: 42.0,
    totalPayout: 490.0,
    suggestedVehicle: 'van',
    status: 'available',
    createdAt: '2026-08-30T09:00:00Z',
    packages: SAMPLE_PACKAGES_SP.slice(5, 17),
  },
];

export const DEFAULT_COMPANY: CompanyProfile = {
  id: 'comp-01',
  name: 'Centro de Distribuição Mercado Express SP',
  cnpj: '18.394.882/0001-94',
  rating: 4.88,
  totalReviews: 84,
  totalFreightsDispatched: 340,
  address: 'Av. Ermano Marchetti, 1000 - Lapa, São Paulo - SP',
  avatar: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=150&auto=format&fit=crop&q=80',
  paymentRating: 4.95,
  dispatchSpeedRating: 4.82,
  verified: true,
  activeSince: 'Março de 2023',
};

export const SAMPLE_COMPANIES: CompanyProfile[] = [
  DEFAULT_COMPANY,
  {
    id: 'comp-02',
    name: 'Farmácias DrogaExpress 24h',
    cnpj: '04.221.730/0001-12',
    rating: 4.92,
    totalReviews: 120,
    totalFreightsDispatched: 580,
    address: 'Rua Pamplona, 500 - Jardim Paulista, São Paulo - SP',
    avatar: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=150&auto=format&fit=crop&q=80',
    paymentRating: 4.98,
    dispatchSpeedRating: 4.9,
    verified: true,
    activeSince: 'Janeiro de 2022',
  },
  {
    id: 'comp-03',
    name: 'Mega Peças Automotivas VUC',
    cnpj: '31.884.105/0001-47',
    rating: 4.75,
    totalReviews: 62,
    totalFreightsDispatched: 210,
    address: 'Rua Guaicurus, 120 - Água Branca, São Paulo - SP',
    avatar: 'https://images.unsplash.com/photo-1553413077-190dd305871c?w=150&auto=format&fit=crop&q=80',
    paymentRating: 4.7,
    dispatchSpeedRating: 4.65,
    verified: true,
    activeSince: 'Agosto de 2023',
  },
];

export const SAMPLE_REVIEWS: Review[] = [
  {
    id: 'rev-01',
    authorRole: 'company',
    authorName: 'Centro de Distribuição Mercado Express SP',
    authorAvatar: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=150&auto=format&fit=crop&q=80',
    targetRole: 'driver',
    targetId: 'drv-01',
    targetName: 'Carlos Eduardo Silva',
    freightId: 'frt-101',
    freightTitle: 'Lote de Entregas E-commerce - Zona Oeste SP',
    rating: 5,
    categoryRatings: {
      punctuality: 5,
      communication: 5,
      careAndCondition: 5,
      speedOrEase: 5,
    },
    tags: ['Pontualidade 100%', 'Cuidado Exemplar', 'Assinaturas Perfeitas', 'Comunicação Rápida'],
    comment:
      'O Carlos é um dos melhores motoristas da nossa malha. Entregou todas as 20 encomendas antes do horário limite, sem nenhuma avaria e com comprovantes digitais preenchidos com foto nítida.',
    wouldRecommend: true,
    createdAt: '2026-08-28T16:30:00Z',
  },
  {
    id: 'rev-02',
    authorRole: 'company',
    authorName: 'Farmácias DrogaExpress 24h',
    authorAvatar: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=150&auto=format&fit=crop&q=80',
    targetRole: 'driver',
    targetId: 'drv-01',
    targetName: 'Carlos Eduardo Silva',
    freightId: 'frt-102',
    freightTitle: 'Entregas Urgentes de Medicamentos',
    rating: 5,
    categoryRatings: {
      punctuality: 5,
      communication: 5,
      careAndCondition: 5,
      speedOrEase: 5,
    },
    tags: ['Super Ágil', 'Medicamento Frágil Seguro', 'Excelente Atendimento'],
    comment:
      'Cumpriu o roteiro otimizado com muita agilidade. Carga de medicamentos transportada na temperatura e integridade exigidas. Recomendamos fortemente para qualquer empresa parceira.',
    wouldRecommend: true,
    createdAt: '2026-08-25T11:20:00Z',
  },
  {
    id: 'rev-03',
    authorRole: 'company',
    authorName: 'Mega Peças Automotivas VUC',
    authorAvatar: 'https://images.unsplash.com/photo-1553413077-190dd305871c?w=150&auto=format&fit=crop&q=80',
    targetRole: 'driver',
    targetId: 'drv-01',
    targetName: 'Carlos Eduardo Silva',
    rating: 4.8,
    categoryRatings: {
      punctuality: 5,
      communication: 4,
      careAndCondition: 5,
      speedOrEase: 5,
    },
    tags: ['Aderência à Rota', 'Veículo Impecável', 'Confiável'],
    comment:
      'Excelente profissional. Fez o check-in do veículo com antecedência e manteve o rastreio ativo durante todo o percurso.',
    wouldRecommend: true,
    createdAt: '2026-08-20T17:45:00Z',
  },
  {
    id: 'rev-04',
    authorRole: 'driver',
    authorName: 'Carlos Eduardo Silva',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    targetRole: 'company',
    targetId: 'comp-01',
    targetName: 'Centro de Distribuição Mercado Express SP',
    freightId: 'frt-101',
    freightTitle: 'Lote de Entregas E-commerce - Zona Oeste / Centro SP',
    rating: 5,
    categoryRatings: {
      punctuality: 5,
      communication: 5,
      careAndCondition: 5,
      speedOrEase: 5,
    },
    tags: ['Doca de Carga Rápida', 'Pagamento Instantâneo PIX', 'Pacotes Bipados e Organizados', 'Equipe Respeitosa'],
    comment:
      'Excelente centro de distribuição! Cheguei na doca e os pacotes já estavam separados por ordem do TSP, com etiquetas QR Code nítidas. Assim que terminei a rota, o pagamento caiu via PIX em menos de 10 minutos.',
    wouldRecommend: true,
    createdAt: '2026-08-28T17:15:00Z',
  },
  {
    id: 'rev-05',
    authorRole: 'driver',
    authorName: 'Carlos Eduardo Silva',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    targetRole: 'company',
    targetId: 'comp-02',
    targetName: 'Farmácias DrogaExpress 24h',
    freightId: 'frt-102',
    freightTitle: 'Entregas Urgentes de Medicamentos - Paulista & Jardins',
    rating: 5,
    categoryRatings: {
      punctuality: 5,
      communication: 5,
      careAndCondition: 5,
      speedOrEase: 5,
    },
    tags: ['Fácil Estacionamento', 'Endereços Precisos', 'Valor Justo do Frete'],
    comment:
      'Empresa séria e transparente. Instruções muito claras para os hospitais e residências. Sempre aceito fretes deles!',
    wouldRecommend: true,
    createdAt: '2026-08-25T12:00:00Z',
  },
];

export const SAMPLE_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-01',
    recipientRole: 'company',
    category: 'delivery',
    type: 'delivery_completed',
    title: 'Entrega Concluída com Sucesso',
    message: 'Carlos Silva entregou o pacote ROTA-BR83921-SP com assinatura digital e foto!',
    timestamp: '2026-08-30T12:35:00Z',
    read: false,
    priority: 'high',
    metadata: {
      trackingCode: 'ROTA-BR83921-SP',
      driverName: 'Carlos Eduardo Silva',
    },
  },
  {
    id: 'notif-02',
    recipientRole: 'driver',
    category: 'freight',
    type: 'new_demand',
    title: 'Novo Frete Disponível na sua Área',
    message: 'Farmácias DrogaExpress publicou 8 paradas (R$ 145,00) a 2.4 km de você.',
    timestamp: '2026-08-30T11:45:00Z',
    read: false,
    priority: 'high',
    metadata: {
      freightId: 'frt-102',
      companyName: 'Farmácias DrogaExpress 24h',
      payout: 145.0,
    },
  },
  {
    id: 'notif-03',
    recipientRole: 'company',
    category: 'route',
    type: 'route_started',
    title: 'Motorista Iniciou a Rota',
    message: 'Carlos Silva iniciou a navegação da rota com 20 entregas (previsão: 2h40m).',
    timestamp: '2026-08-30T11:00:00Z',
    read: true,
    priority: 'normal',
    metadata: {
      driverName: 'Carlos Eduardo Silva',
    },
  },
  {
    id: 'notif-04',
    recipientRole: 'both',
    category: 'review',
    type: 'review_received',
    title: 'Nova Avaliação 5 Estrelas Recebida! ⭐',
    message: 'Você recebeu uma avaliação 5.0 estrelas com o elogio "Pontualidade 100%".',
    timestamp: '2026-08-30T09:15:00Z',
    read: true,
    priority: 'normal',
    metadata: {
      rating: 5,
    },
  },
  {
    id: 'notif-05',
    recipientRole: 'driver',
    category: 'finance',
    type: 'payment_confirmed',
    title: 'Repasse PIX Confirmado',
    message: 'R$ 368,00 creditados na sua conta referente ao frete de ontem.',
    timestamp: '2026-08-29T18:20:00Z',
    read: true,
    priority: 'normal',
    metadata: {
      payout: 368.0,
    },
  },
];

export const DEFAULT_NOTIFICATION_PREFERENCES: NotificationPreferences = {
  soundEnabled: true,
  browserPushEnabled: false,
  newDemands: true,
  routeUpdates: true,
  deliveryConfirmations: true,
  reviewsAndRatings: true,
  paymentsAndPix: true,
  demandRadiusKm: 15,
};
